# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ecdef5652d8461931a12dd5c435238f125591b25efe6e8856abfb4c0bca9d9827f5000608d9982079f4ea266c40a88b19427c2cc956b259d2bff1c1fbe9b6594

test:
  secret_key_base: 26ed57d5266d57391134c341308d7090fc346012e3c6f8fdd59d422558296862fb5d3d1bead0d2f560f08a53d89f01b46961ec51f61331c3516b2399e345ea80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
